// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://toyiwxabozkwzfrlgyjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRveWl3eGFib3prd3pmcmxneWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2Mjk2MzgsImV4cCI6MjA4MTIwNTYzOH0.ZURjq12cCrMsW87yOEtBpoNbyQYCQI01818enNg9fos";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});